services:
    database:
        build: ./Database
        container_name: td1-database
        restart: on-failure
        networks:
            - db-network
        env_file: .env
       

    backend:
        build: ./Backend_API/simpleapi
        container_name: td1-backend
        restart: on-failure
        networks:
            - db-network
            - api-network
        env_file: .env
        environment:
            - DB_HOST=td1-database
            - POSTGRES_USER=usr
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_DB=db
        depends_on:
           - database

    frontend:
        build: ./Frontend
        container_name: td1-frontend
        restart: on-failure
        networks:
            - api-network
        depends_on:
            - backend

    httpd:
        build: ./HTTP_server
        container_name: td1-httpd
        restart: on-failure
        networks:
            - api-network
        ports:
            - "8070:80"
        depends_on:
           - frontend
           - backend
networks:
    db-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.1.0/24
    api-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.2.0/24

volumes:
    db_data:
        driver: local