---
- name: Wait for frontend to be healthy before launching proxy
  shell: |
    docker inspect --format='{{"{{"}} .State.Health.Status {{"}}"}}' td1-frontend
  register: health_status
  until: health_status.stdout == "healthy"
  retries: 12
  delay: 10

- name: Wait for backend to be healthy before launching proxy
  shell: |
    docker inspect --format='{{"{{"}} .State.Health.Status {{"}}"}}' td1-backend
  register: health_status
  until: health_status.stdout == "healthy"
  retries: 12
  delay: 10

- name: Launch HTTP Server (Reverse Proxy) container
  docker_container:
    name: td1-httpd
    image: "{{ docker_user }}/td1-httpd"
    state: started
    pull: true
    recreate: true
    restart_policy: always
    networks:
      - name: api-network
        aliases:
          - td1-httpd
    ports:
      - "80:80"