---
# tasks file for launch_app role

- name: Launch Backend API container
  docker_container:
    name: td1-backend
    image: cdmrg/td1-backend
    state: started
    restart_policy: always
    networks:
      - name: db-network
      - name: api-network
    ports:
      - "8080:8080"
    env:
      POSTGRES_HOST: td1-database
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

- name: Wait for application to be ready
  pause:
    seconds: 15
