---
# tasks file for launch_database role

- name: Create database volume
  docker_volume:
    name: db_data
    state: present

- name: Launch PostgreSQL database container
  docker_container:
    name: td1-database
    image: cdmrg/td1-database
    state: started
    restart_policy: always
    networks:
      - name: db-network
    ports:
      - "5432:5432"
    volumes: db_data:/var/lib/postgresql/data
    env:
      POSTGRES_HOST: td1-database
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr"]
      interval: 10s
      timeout: 5s
      retries: 5

- name: Wait for database to be ready
  pause:
    seconds: 10
